spring.application.name=bolsoseguro
spring.jpa.hibernate.ddl-auto=validate


spring.datasource.url=jdbc:mysql://edumysql.acesso.rj.senac.br/20261_prjint4_manha_bolsoseguro
spring.datasource.username=20261_prjint4_manha
spring.datasource.password=senac@12938


spring.jpa.show-sql=true

server.port=8080